# Generated by scripts/update.py; do not edit by hand.
class Pretty < Formula
  desc "Fast terminal emulator with friendly branding"
  homepage "https://github.com/pg83/shitty"
  version "7"
  url "https://github.com/pg83/shitty/releases/download/7/pt-darwin-arm64.tar.gz"
  sha256 "f72f9eb3ea6d21dc86d0beaf6d64956850ac4351abdcffa57404fc985c052db4"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "pt"
  end

  test do
    assert_match "Pretty", shell_output("#{bin}/pt -version")
  end
end
