# Generated by scripts/update.py; do not edit by hand.
class Pretty < Formula
  desc "Fast terminal emulator with friendly branding"
  homepage "https://github.com/pg83/shitty"
  version "16"
  url "https://github.com/pg83/shitty/releases/download/16/pt-darwin-arm64.tar.gz"
  sha256 "67853149dd4386bf3286b387d9efbcd453615c8c8cd644707abf4ed23a0e1e28"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "pt"
  end

  test do
    assert_match "Pretty", shell_output("#{bin}/pt -version")
  end
end
