# Generated by scripts/update.py; do not edit by hand.
class Pretty < Formula
  desc "Fast terminal emulator with friendly branding"
  homepage "https://github.com/pg83/shitty"
  version "10"
  url "https://github.com/pg83/shitty/releases/download/10/pt-darwin-arm64.tar.gz"
  sha256 "295df09847ef90d0f4e7fa717498db3ec47bb3e46fc5b3725258fbf900f964b3"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "pt"
  end

  test do
    assert_match "Pretty", shell_output("#{bin}/pt -version")
  end
end
