# Generated by scripts/update.py; do not edit by hand.
class Shitty < Formula
  desc "Fastest terminal emulator on Earth"
  homepage "https://github.com/pg83/shitty"
  version "17"
  url "https://github.com/pg83/shitty/releases/download/17/st-darwin-arm64.tar.gz"
  sha256 "7c8de9aba12079ae653c54343f86daecbfe06767a8e0ceafecbc3ee3064c275d"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "st"
  end

  test do
    assert_match "Shitty", shell_output("#{bin}/st -version")
  end
end
