# Generated by scripts/update.py; do not edit by hand.
class Shitty < Formula
  desc "Fastest terminal emulator on Earth"
  homepage "https://github.com/pg83/shitty"
  version "15"
  url "https://github.com/pg83/shitty/releases/download/15/st-darwin-arm64.tar.gz"
  sha256 "b80098b98afe21698f3a034166e14b6d1c6daac76549ec62edd1447f94037fcf"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "st"
  end

  test do
    assert_match "Shitty", shell_output("#{bin}/st -version")
  end
end
