# Generated by scripts/update.py; do not edit by hand.
class Shitty < Formula
  desc "Fastest terminal emulator on Earth"
  homepage "https://github.com/pg83/shitty"
  version "12"
  url "https://github.com/pg83/shitty/releases/download/12/st-darwin-arm64.tar.gz"
  sha256 "d0e90c2dd56db22ea3d1dac467a65cdef4be6867a7a2330b6c61792dab103bf8"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "st"
  end

  test do
    assert_match "Shitty", shell_output("#{bin}/st -version")
  end
end
