#!/usr/bin/env python3
"""Reconcile the terminal formulae with the shitty releases.

With a tag argument, rewrites the formulae for that release. Without one,
resolves the latest release and exits quietly when the formulae already
match - the shape the scheduled reconcile workflow runs in.
"""

import hashlib
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


RELEASES = "https://api.github.com/repos/pg83/shitty/releases"
ROOT = Path(__file__).resolve().parent.parent
FORMULAE = (
    {
        "path": ROOT / "Formula" / "shitty.rb",
        "class_name": "Shitty",
        "description": "Fastest terminal emulator on Earth",
        "asset": "st-darwin-arm64.tar.gz",
        "binary": "st",
        "brand": "Shitty",
    },
    {
        "path": ROOT / "Formula" / "pretty.rb",
        "class_name": "Pretty",
        "description": "Fast terminal emulator with friendly branding",
        "asset": "pt-darwin-arm64.tar.gz",
        "binary": "pt",
        "brand": "Pretty",
    },
)
FORMULA = """\
# Generated by scripts/update.py; do not edit by hand.
class {class_name} < Formula
  desc "{description}"
  homepage "https://github.com/pg83/shitty"
  version "{tag}"
  url "{url}"
  sha256 "{sha256}"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "{binary}"
  end

  test do
    assert_match "{brand}", shell_output("#{{bin}}/{binary} -version")
  end
end
"""


def fetch_json(url: str) -> dict:
    request = urllib.request.Request(
        url,
        headers={"Accept": "application/vnd.github+json"},
    )
    with urllib.request.urlopen(request) as response:
        return json.load(response)


def release(tag: str | None) -> dict:
    if tag is None:
        return fetch_json(f"{RELEASES}/latest")
    escaped_tag = urllib.parse.quote(tag, safe="")
    try:
        return fetch_json(f"{RELEASES}/tags/{escaped_tag}")
    except urllib.error.HTTPError as error:
        if error.code == 404:
            raise RuntimeError(f"release does not exist: {tag}") from error
        raise


def formula_tag(formula: Path) -> str | None:
    if not formula.exists():
        return None
    match = re.search(r'^  version "([0-9]+)"$', formula.read_text(), re.M)
    return match.group(1) if match else None


def asset_url(release_data: dict, name: str) -> str | None:
    for asset in release_data["assets"]:
        if asset["name"] == name:
            return asset["browser_download_url"]
    return None


def sha256(url: str) -> str:
    digest = hashlib.sha256()
    with urllib.request.urlopen(url) as response:
        while chunk := response.read(1 << 20):
            digest.update(chunk)
    return digest.hexdigest()


def update_formula(specification: dict, release_data: dict) -> bool:
    tag = release_data["tag_name"]
    formula = specification["path"]
    url = asset_url(release_data, specification["asset"])
    if url is None:
        print(
            f"release {tag} has no {specification['asset']}; "
            f"leaving {formula.name} unchanged"
        )
        return False
    if formula_tag(formula) == tag:
        print(f"{formula.name} already at {tag}")
        return False

    digest = sha256(url)
    formula.write_text(
        FORMULA.format(
            **specification,
            tag=tag,
            url=url,
            sha256=digest,
        )
    )
    print(f"updated {formula} to {tag} ({digest})")
    return True


def main() -> int:
    if len(sys.argv) > 2 or (len(sys.argv) == 2 and not sys.argv[1].isdigit()):
        raise SystemExit(__doc__)
    requested_tag = sys.argv[1] if len(sys.argv) == 2 else None
    release_data = release(requested_tag)
    for specification in FORMULAE:
        update_formula(specification, release_data)
    return 0


if __name__ == "__main__":
    sys.exit(main())
