#!/usr/bin/env python3
"""Regenerate Formula/shitty.rb for a shitty release tag.

Downloads the release's binary archive, hashes it, and rewrites the
formula. Run by the update workflow on a repository_dispatch from the
shitty repository, or by hand: scripts/update.py TAG.
"""

import hashlib
import sys
import urllib.request
from pathlib import Path

ASSET = "st-darwin-arm64.tar.gz"
FORMULA = """\
# Generated by scripts/update.py; do not edit by hand.
class Shitty < Formula
  desc "Fastest terminal emulator on Earth"
  homepage "https://github.com/pg83/shitty"
  version "{tag}"
  url "{url}"
  sha256 "{sha256}"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "st"
  end

  test do
    assert_match "Shitty", shell_output("#{{bin}}/st -version")
  end
end
"""


def main() -> int:
    if len(sys.argv) != 2 or not sys.argv[1].isdigit():
        raise SystemExit(__doc__)
    tag = sys.argv[1]
    url = f"https://github.com/pg83/shitty/releases/download/{tag}/{ASSET}"
    digest = hashlib.sha256()
    with urllib.request.urlopen(url) as response:
        while chunk := response.read(1 << 20):
            digest.update(chunk)
    formula = Path(__file__).resolve().parent.parent / "Formula" / "shitty.rb"
    formula.write_text(FORMULA.format(tag=tag, url=url, sha256=digest.hexdigest()))
    print(f"updated {formula} to {tag} ({digest.hexdigest()})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
