#!/usr/bin/env python3
"""Reconcile Formula/shitty.rb with the shitty releases.

With a tag argument, rewrites the formula for that release. Without one,
resolves the latest release and exits quietly when the formula already
matches - the shape the scheduled reconcile workflow runs in.
"""

import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

ASSET = "st-darwin-arm64.tar.gz"
RELEASES = "https://api.github.com/repos/pg83/shitty/releases/latest"
FORMULA = """\
# Generated by scripts/update.py; do not edit by hand.
class Shitty < Formula
  desc "Fastest terminal emulator on Earth"
  homepage "https://github.com/pg83/shitty"
  version "{tag}"
  url "{url}"
  sha256 "{sha256}"
  license any_of: ["MIT", "GPL-3.0-or-later"]

  depends_on :macos
  depends_on arch: :arm64

  def install
    bin.install "st"
  end

  test do
    assert_match "Shitty", shell_output("#{{bin}}/st -version")
  end
end
"""


def latest_tag() -> str:
    with urllib.request.urlopen(RELEASES) as response:
        return json.load(response)["tag_name"]


def formula_tag(formula: Path) -> str | None:
    match = re.search(r'^  version "([0-9]+)"$', formula.read_text(), re.M)
    return match.group(1) if match else None


def main() -> int:
    if len(sys.argv) > 2 or (len(sys.argv) == 2 and not sys.argv[1].isdigit()):
        raise SystemExit(__doc__)
    tag = sys.argv[1] if len(sys.argv) == 2 else latest_tag()
    formula = Path(__file__).resolve().parent.parent / "Formula" / "shitty.rb"
    if formula_tag(formula) == tag:
        print(f"formula already at {tag}")
        return 0
    url = f"https://github.com/pg83/shitty/releases/download/{tag}/{ASSET}"
    digest = hashlib.sha256()
    with urllib.request.urlopen(url) as response:
        while chunk := response.read(1 << 20):
            digest.update(chunk)
    formula.write_text(FORMULA.format(tag=tag, url=url, sha256=digest.hexdigest()))
    print(f"updated {formula} to {tag} ({digest.hexdigest()})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
